version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mail
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./app/google-metadata:/var/www/google-metadata
